site_name: Sympyfy Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: light blue

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          show_signature: true
          show_root_full_path: false
          show_symbol_type_toc: true
          show_root_heading: true
          docstring_section_style: table

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.superfences


copyright: |
  &copy; 2024 <a href="https://github.com/acpirience"  target="_blank" rel="noopener">Acpirience</a>